### ISSUE TITLE
Infinite loading while login in using google login.

### ISSUE THREAD

**Issue by apatnaik93** [auth0-samples/auth0-ionic2-samples#42]
I am clicking the login button in home page followed by login using my google account. When I click the google login button it goes to infinite loading page.

**Comment by gabedeko** [comment]
I'm having the same issue and have contacted Auth0 about it but haven't received a response yet.

**Comment by texano00** [comment]
```ionic info```

```
cli packages: (/home/yuri/.nvm/versions/node/v8.9.4/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 7.0.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.9.4
    npm               : 5.6.0 
    OS                : Linux 4.13

Environment Variables:

    ANDROID_HOME : /home/yuri/Android/Sdk

Misc:

    backend : pro
```

same issue.
The callback to the app seems to not work well.
The login is done correctly looking on Auth0 Dashboard.

**Comment by texano00** [comment]
I've resolved my issue of infinite loading.
The problem comes from the stupid error of leaving brackets in

`
ionic cordova plugin add cordova-plugin-customurlscheme --variable URL_SCHEME={YOUR_PACKAGE_ID} --variable ANDROID_SCHEME={YOUR_PACKAGE_ID} --variable ANDROID_HOST={YOUR_AUTH0_DOMAIN} --variable ANDROID_PATHPREFIX=/cordova/{YOUR_PACKAGE_ID}/callback
`.
